### ISSUE TITLE
Make the game window responsive

### ISSUE THREAD

**Issue by abidurrahman11** [abidurrahman11/Pygame-Racing-Car#18]
Currently the game window has a fixed height & width which is not responsive. Make it responsive so that player can resize the screen.

**Comment by TristanGaldys** [comment]
Hey There, I happened to stumble upon this project and it seemed like something I could do and I've never done A PR so I assumed this would be a good first one. Hopefully you like my changes.
I would recommend having a pause menu because it's really hard to resize while playing. I just scaled everything with the window.

**Comment by abidurrahman11** [comment]
Hey @TristanGaldys 
I will review your PR and assign you soon.
Thanks.
